development:
    adapter: postgresql
    encoding: unicode
    database: database_postgresql
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: database_postgresql_test
    pool: 5

production:
    adapter: postgresql
    encoding: unicode
    database: database_postgresql
    pool: 5
